### ISSUE TITLE
Prettify DOIs?

### ISSUE THREAD

**Issue by iandol** [pandoc-ext/pretty-urls#1]
Hi, DOIs could also be improved by labelling them using something like `DOI:` and removing the domain name. This can be done adding one line:

```lua
link.content = link.target:gsub('^https%:%/%/', '')
link.content = link.content:gsub('^(dx%.?)doi%.org%/', 'DOI:') --prettify DOIs
```

Maybe this is out-of-scope, but it does make academic reference links prettier!

**Comment by tarleb** [comment]
I like that! Do you want to make a PR?

**Comment by tarleb** [comment]
Closed by #2.

**Comment by iandol** [comment]
Thanks @tarleb! I have personally removed the insecure markers as for whatever reason many of my bibliographic databases return http: as a default (which is almost always redirected to https:) so my bibliographies would end up with locks everywhere. But I certainly understand why you put this as a default. And thanks as always for all your work on Pandoc and its ecosystem!

**Comment by tarleb** [comment]
I'm steering off topic, but out of interest: My assumption was that this filter would typically be run before `--citeproc`, as otherwise it will interfere with the citation style. Is my assumption wrong?

**Comment by iandol** [comment]
> I'm steering off topic, but out of interest: My assumption was that this filter would typically be run before `--citeproc`, as otherwise it will interfere with the citation style. Is my assumption wrong?

No I think in general that assumption is correct. BUT for some lazy users like me who want to ensure minified doi links but don't want to edit CSL styles, being able to swap the order gives  us our few minutes extra for procrastination 😅

**Comment by tarleb** [comment]
Hahaha, fair! :joy: :+1:
